language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
env:
  - XHPROF_VERSION="4.1.5"
  - XHPROF_VERSION="4.1.7"

matrix:
  exclude:
    - php: 7.0
      env: XHPROF_VERSION="4.1.5"
    - php: 7.1
      env: XHPROF_VERSION="4.1.5"
    - php: 7.2
      env: XHPROF_VERSION="4.1.5"
    - php: 7.3
      env: XHPROF_VERSION="4.1.5"

before_script:
  - wget --no-check-certificate https://github.com/tideways/php-xhprof-extension/archive/v${XHPROF_VERSION}.tar.gz && tar zxvf v${XHPROF_VERSION}.tar.gz
  - cd php-xhprof-extension-${XHPROF_VERSION} && phpize && ./configure && make && make install && cd ..
  - echo "extension=tideways.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "tideways.auto_prepend_library=0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - if [[ $TRAVIS_PHP_VERSION == 5.6 ]]; then composer require --dev phpunit/phpunit "^5" --ignore-platform-reqs --quiet; fi
  - if [[ $TRAVIS_PHP_VERSION == 7.0 ]]; then composer require --dev phpunit/phpunit "^6" --ignore-platform-reqs --quiet; fi 
  - if [[ $TRAVIS_PHP_VERSION > 7.0 ]]; then composer require --dev phpunit/phpunit "^7" --ignore-platform-reqs --quiet; fi 
  - composer install --prefer-dist --dev --ignore-platform-reqs

script: ./vendor/bin/phpunit